#!/usr/bin/env node
/**
 * Copies shared pages from packages/pages/ into the current app's src/app/.
 * Skips files that already exist locally (store-specific overrides).
 * Run from an app directory: node ../../scripts/inject-pages.mjs
 *
 * For dev: use --watch to re-copy on changes for hot reload.
 */

import fs from 'fs'
import path from 'path'

const appDir = process.cwd()
const targetDir = path.join(appDir, 'src/app')
const pagesDir = path.resolve(appDir, '../../packages/pages')
const libDir = path.resolve(appDir, '../../packages/lib')

// Shared src/-level files (not inside src/app/) injected directly into src/
const sharedSrcFiles = [
  { src: path.join(libDir, 'middleware.ts'), dest: path.join(appDir, 'src/middleware.ts') },
]
const watch = process.argv.includes('--watch')

if (!fs.existsSync(pagesDir)) {
  console.error('packages/pages not found at', pagesDir)
  process.exit(1)
}

function inject() {
  const manifest = []

  function walk(dir, base = '') {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const rel = base ? `${base}/${entry.name}` : entry.name
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(full, rel)
      } else if (entry.name === 'package.json') {
        continue
      } else {
        const dest = path.join(targetDir, rel)

        // Skip if a real non-injected file exists — it's a local override
        // We check the manifest to know if we previously injected it
        const isOurFile = fs.existsSync(dest) && isInjected(rel)
        if (fs.existsSync(dest) && !isOurFile) {
          continue
        }

        fs.mkdirSync(path.dirname(dest), { recursive: true })
        fs.copyFileSync(full, dest)
        manifest.push(rel)
      }
    }
  }

  walk(pagesDir)

  const manifestPath = path.join(targetDir, '.injected')
  fs.writeFileSync(manifestPath, manifest.join('\n') + '\n')

  // Write a .gitignore so injected files are never committed
  const escaped = manifest.map(f => f.replace(/\[/g, '\\[').replace(/\]/g, '\\]'))
  const ignoreLines = ['# Auto-generated by inject-pages.mjs', '.injected', '.gitignore', ...escaped]
  fs.writeFileSync(path.join(targetDir, '.gitignore'), ignoreLines.join('\n') + '\n')

  return manifest.length
}

function isInjected(rel) {
  const manifestPath = path.join(targetDir, '.injected')
  if (!fs.existsSync(manifestPath)) return false
  const files = fs.readFileSync(manifestPath, 'utf8').trim().split('\n')
  return files.includes(rel)
}

// Inject shared src/-level files (e.g. middleware.ts)
function injectSrcFiles() {
  for (const { src, dest } of sharedSrcFiles) {
    if (!fs.existsSync(src)) continue
    fs.copyFileSync(src, dest)
  }
}

const count = inject()
injectSrcFiles()
console.log(`Injected ${count} shared pages`)

if (watch) {
  console.log('Watching packages/pages/ and packages/lib/ for changes...')
  fs.watch(pagesDir, { recursive: true }, (_event, filename) => {
    if (!filename || filename === 'package.json') return
    const src = path.join(pagesDir, filename)
    const dest = path.join(targetDir, filename)
    if (fs.existsSync(src) && isInjected(filename)) {
      fs.copyFileSync(src, dest)
      console.log(`Updated ${filename}`)
    }
  })
  fs.watch(libDir, { recursive: false }, (_event, filename) => {
    const match = sharedSrcFiles.find(f => path.basename(f.src) === filename)
    if (match && fs.existsSync(match.src)) {
      fs.copyFileSync(match.src, match.dest)
      console.log(`Updated src/${filename}`)
    }
  })
}
